version: '3'
services:
  wiremock:
    image: wiremock/wiremock:latest
    container_name: my-wiremock-demo
    ports:
      - "8080:8080"
    volumes:
      - ./mappings:/home/wiremock/mappings
      - ./__files:/home/wiremock/__files
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m
    restart: always